<!DOCTYPE html>
<html class="gr__manish3499_github_io" lang="en-US"><head>
    <meta charset="UTF-8">

<!-- Begin Jekyll SEO tag v2.5.0 -->
<title>parallelization-of-JPF</title>
<meta name="generator" content="Jekyll v3.8.5">
<meta property="og:title" content="parallelization-of-JPF">
<meta property="og:locale" content="en_US">
<link rel="canonical" href="https://manish3499.github.io/parallelization-of-JPF/">
<meta property="og:url" content="https://manish3499.github.io/parallelization-of-JPF/">
<meta property="og:site_name" content="parallelization-of-JPF">
<script type="application/ld+json">
{"headline":"parallelization-of-JPF","@type":"WebSite","url":"https://manish3499.github.io/parallelization-of-JPF/","name":"parallelization-of-JPF","@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#157878">
    <link rel="stylesheet" href="/parallelization-of-JPF/assets/css/style.css?v=0ce7b32d21a58a944d47227b1e3601531ca12914">
  </head>
  <body data-gr-c-s-loaded="true">
    <section class="page-header">
      <h1 class="project-name">parallelization-of-JPF</h1>
      <h2 class="project-tagline"></h2>
      
        <a href="https://github.com/manish3499/parallelization-of-JPF" class="btn">View on GitHub</a>
      
      
    </section>

    <section class="main-content">
    
    <h2>About JPF and the project</h2>
<p>The Java Pathfinder Team is an open-source organization which maintains and contributes to the project named Java Pathfinder (JPF) which was initially implemented by NASA in 1999 to verify safety and mission-critical software for its space missions. JPF was made open source in 2005, and since then it has seen vast applications in many industries.</p>
<p>JPF is a model checking software, which uses a brute force technique to find any errors in a given piece of java code. To perform this, JPF uses symbolic execution and finds errors by finding out property violations while executing all the different execution paths possible. This is quite a slow process, and the purpose of this project is to parallelize the execution to make the error detection faster by making use of multicore processors.</p>
<p>This project is done under the Google Summer of Code program which is a three-month-long program conducted by Google every year, where students all around the world get the opportunity to work on open source projects under the supervision of experienced mentors</p>
      


      <footer class="site-footer">
        
          <span class="site-footer-owner"><a href="https://github.com/manish3499/parallelization-of-JPF">parallelization-of-JPF</a> is maintained by <a href="https://github.com/manish3499">manish3499</a>.</span>
        
        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
      </footer>
    </section>

    
  

</body>
</html>
